platform :ios, '9.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        # The following is needed to ensure the "archive" step works in XCode.
        # It removes React & Yoga from the Pods project, as it is already included in the main project.
        # Without this, you'd see errors when you archive like:
        # "Multiple commands produce ... libReact.a"
        # "Multiple commands produce ... libyoga.a"
        
        targets_to_ignore = %w(React yoga)
        
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
        
    end
end

target 'BalanceWallet' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage'
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'RNLanguages', :path => '../node_modules/react-native-languages'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  # Required by Google Map, ignore if you use Apple Map
  pod 'GoogleMaps', '2.5.0'
  pod 'Google-Maps-iOS-Utils', '2.1.0'
  pod 'GoogleUtilities', '5.3.7'
  pod 'GoogleAppMeasurement', '5.4'
  
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path # <~~ if you need GoogleMaps support on iOS
  
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

end
